openapi: 3.0.1
info:
  title: JC - Watsonx AI API
  contact:
    name: Joe Cosenza
    email: jcosenz@us.ibm.com
  x-ibm-application-name: JC - Watsonx AI API
  x-ibm-application-id: JC-WatsonxAIAPI
  description: Allows you to perform API calls to Watsonx AI
  x-ibm-application-icon: <svg width="30" height="30" id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 400 360"><defs><style>.cls-1{fill:#f8b500;}.cls-2{fill:#231815;}</style></defs><title>JRK number</title><path class="cls-1" d="M354.6,295.5H39.4A39.4,39.4,0,0,1,0,256.1V39.4A39.4,39.4,0,0,1,39.4,0H354.6A39.4,39.4,0,0,1,394,39.4V256.1a39.4,39.4,0,0,1-39.4,39.4"/><path class="cls-2" d="M105.85,44.44h45.42V171.75c0,57.37-27.49,77.4-71.72,77.4-10.46,0-24.21-1.8-33.17-4.78l5.08-36.76a74.94,74.94,0,0,0,23.31,3.58c19.12,0,31.08-8.66,31.08-40Z"/><path class="cls-2" d="M337.15,240.18c-8.37,4.19-27.19,8.67-51.7,8.67C215.82,248.85,180,205.52,180,148.14c0-68.74,49-107,110-107,23.6,0,41.53,4.78,49.6,9l-9.26,36.16A98.32,98.32,0,0,0,292,78.81c-36.16,0-64.25,21.81-64.25,66.64,0,40.34,23.9,65.74,64.55,65.74,13.74,0,29-3,37.95-6.57Z"/></svg>
  version: latest
servers:
  - url: "https://us-south.ml.cloud.ibm.com"
security:
#To authorize you must connect the app with "Bearer <Your bearer token>"
#To obtain a bearer token, you must generate an API key in IBM Cloud
#Once you obtain your API key run this call to obtain your Bearer Token using your API Key
#curl -X POST 'https://iam.cloud.ibm.com/identity/token' -H 'Content-Type: application/x-www-form-urlencoded' -d 'grant_type=urn:ibm:params:oauth:grant-type:apikey&apikey=<Your API Key>'
#https://cloud.ibm.com/apidocs/watson-data-api#connections
  - bearerAuth: []
paths:
  "/ml/v1-beta/generation/text?version=2023-05-29":
    post:
      summary: JC - Send a prompt to Watsonx AI
      description: Send a prompt to Watsonx AI
      operationId: watsonxAIAPI
      requestBody:
        description: Send generation request
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/requestBody"
      responses:
        "202":
          description: Request accepted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/response"
        "401":
          description: Request denied
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        "403":
          description: Request denied, out of tokens
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
components:
  schemas:
    requestBody:
      type: object
      required:
        - input
      properties:
        model_id:
          x-ibm-label: Foundation Model
          description: Select a model that best fits your needs. All models support English text. Check the model information for other supported languages.
          #x-ibm-show: false
          type: string
          default: "google/flan-ul2"
          enum:
            - "google/flan-ul2"
            - "google/flan-t5-xxl"
            - "eleutherai/gpt-neox-20b"
            - "ibm/mpt-7b-instruct"
            - "bigcode/starcoder"
            - "bigscience/mt0-xxl"
        input:
          type: string
          x-ibm-multiline: "true"
          x-ibm-label: Watsonx AI Prompt
          default: "Enter your text here in a prompt form"
        parameters:
          $ref: "#/components/schemas/parameters"
        project_id:
          x-ibm-disable: true
          x-ibm-show: false
          type: string
          default: "a7d3a036-8d74-4d27-b312-3eada98ea204"
    response:
      description: Successful response
      type: object
      properties:
        results:
          x-ibm-label: Watsonx AI Says
          type: array
          items:
            type: object
            properties: 
                generated_text:
                  x-ibm-label: Results
                  type: string
    errorResponse:
      description: Unsuccessful response
      type: object
      properties:
        errors:
          x-ibm-label: Error
          type: array
          items:
            type: object
            properties:
                message:
                    type: string
    parameters:
      type: object
      properties:
        decoding_method:
          x-ibm-label: Decoding Method
          description: Set decoding to "greedy" to always select words with the highest probability. Set decoding to "sample" to customize the variability of word selection.
          #x-ibm-show: false
          type: string
          default: "greedy"
          enum:
            - "greedy"
            - "sample"
        max_new_tokens:
          x-ibm-label: Max Tokens
          description: Define the maximum number of tokens to generate.
          #x-ibm-show: false
          type: integer
          format: int32
          default: 700
        min_new_tokens:
          x-ibm-label: Min Tokens
          description: If stop sequences are given, they are ignored until minimum number of tokens are generated.
          #x-ibm-show: false
          type: integer
          format: int32
          default: 100
        repetition_penalty:
          x-ibm-label: Repitition Penalty
          description: Penalty for repetition penalty. 1.00 means no penalty.
          #x-ibm-show: false
          type: number
          default: 1.00
          minimum: 1.00
          maximum: 2.00
        temperature: 
          x-ibm-label: Temperature
          description: Sample Method - Control the creativity of generated text. Higher values will lead to more randomly generated outputs.
          #x-ibm-show: false
          type: number
          default: 0.18
          minimum: 0
          maximum: 2
        top_k: 
          x-ibm-label: Top K
          description: Sample Method - Set the number of highest probability tokens to keep for top-k filtering. Lower values make it less likely the model will go off topic.
          #x-ibm-show: false
          type: integer
          format: int32
          default: 50
          minimum: 0
          maximum: 100
        top_p: 
          x-ibm-label: Top P (Nucleus Sampling)
          description: Sample Method - If < 1.0, only the smallest set of probable tokens with probabilities that add up to "top-p" or higher are used.
          #x-ibm-show: false
          type: number
          default: 1.00
          minimum: 0
          maximum: 1.00
        random_seed:
          x-ibm-label: Random Seed
          description: Sample Method- Controls the random sampling of the generated tokens when sampling is enabled. Setting the random seed to the same number for each generation ensures experimental repeatability.
          #x-ibm-show: false
          type: integer
        stop_sequences:
          x-ibm-label: Stop Sequences
          description: Stop sequences are one or more strings which will cause the text generation to stop if/when they are produced as part of the output. Stop sequences encountered prior to the minimum number of tokens being generated will be ignored.
          type: array
          #x-ibm-show: false
          items:
            type: string
  securitySchemes:
    bearerAuth:
      type: apiKey
      in: header
      name: Authorization