openapi: 3.0.1
info:
  title: JC - Automation Document Processing API
  contact:
    name: Joe Cosenza
    email: jcosenz@us.ibm.com
    url: https://ibm-client-engineering.github.io/solution-wxo/watsonx
  x-ibm-application-name: JC - ADP API
  x-ibm-application-id: JC-ADPAPI
  description: Enables the ability to send files to ADP for document processing and retrieve the results
  version: latest
externalDocs:
  url: https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/23.0.2?topic=integrations-automation-document-processing-api
servers:
  - url: "https://{serverName}.cloud.ibm.com"
    variables:
      serverName:
        default: "ADP Server"
security:
  - bearerAuth: []
paths:
  "/v1/projects/{project_id}/analyzers":
    post:
      summary: JC - Send a PDF to ADP
      description: Send a PDF to ADP
      operationId: sendPDF
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
            x-ibm-disable: true
            x-ibm-show: false
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/requestBody"
      responses:
        '202':
          description: Success. Request has been processed successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/sendPDFResponse"
        '400':
          description: Invalid Request. Invalid parameter requests.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        '401':
          description: Unauthorized. Invalid apiKey or missing Zen token.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        '500':
          description: Internal Server Error. Unknown Internal Server Error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        '502':
          description: Bad Gateway, ADP Server is down.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        '503':
          description: Unavailable service. ADP Server is overloaded with requests.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        '504':
          description: Gateway timeout. Did not receive a timely response from the server.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
  "/v1/projects/{project_id}/analyzers/{analyzerId}":
    get:
      summary: JC - Get ADP Status
      description: Get ADP Status
      operationId: getStatus
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
            x-ibm-disable: true
            x-ibm-show: false
        - name: analyzerId
          in: path
          required: true
          schema:
            type: string
            x-ibm-disable: true
            x-ibm-show: false
      responses:
        '200':
          description: Success. Request has been processed successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getstatusResponse"
        '400':
          description: Invalid Request. Invalid parameter requests.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        '401':
          description: Unauthorized. Invalid apiKey or missing Zen token.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        '404':
          description: Failed. Content not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        '500':
          description: Internal Server Error. Unknown Internal Server Error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        '502':
          description: Bad Gateway, ADP Server is down.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        '503':
          description: Unavailable service. ADP Server is overloaded with requests.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        '504':
          description: Gateway timeout. Did not receive a timely response from the server.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
  "/v1/projects/{project_id}/analyzers/{file_id}/json/basic":
    get:
      summary: JC - Get ADP Results
      description: Get ADP Results
      operationId: getResults
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
            x-ibm-disable: true
            x-ibm-show: false
        - name: file_id
          in: path
          required: true
          schema:
            type: string
            x-ibm-disable: true
            x-ibm-show: false
      responses:
        '200':
          description: Success. Request has been processed successfully.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/getresultsResponse"
        '400':
          description: Invalid Request. Invalid parameter requests.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        '401':
          description: Unauthorized. Invalid apiKey or missing Zen token.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        '404':
          description: Failed. Content not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        '500':
          description: Internal Server Error. Unknown Internal Server Error.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        '502':
          description: Bad Gateway, ADP Server is down.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        '503':
          description: Unavailable service. ADP Server is overloaded with requests.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
        '504':
          description: Gateway timeout. Did not receive a timely response from the server.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
components:
  schemas:
    requestBody:
      type: object
      properties:
        content:
          type: string
          format: binary
          title: File content
          description: >-
            Upload a PDF
          x-ibm-content: {}
    sendPDFResponse:
      description: Successful response
      type: object
      properties:
        results:
          type: array
          items:
            type: object
            properties:
              data:
                properties:
                  filenamein:
                    type: string
                  analyzerid:
                    type: string
    getstatusResponse:
      description: Successful response
      type: object
    getresultsResponse:
      description: Successful response
      type: object
    errorResponse:
      description: Unsuccessful response
      type: object
      properties:
        error:
          type: string
        error_description:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: IBM CP4BA Zen API Key