openapi: 3.0.1
info:
  title: JC - Automation Document Processing API
  contact:
    name: Joe Cosenza
    email: jcosenz@us.ibm.com
    url: https://ibm-client-engineering.github.io/solution-wxo/watsonx
  x-ibm-application-name: JC - ADP API
  x-ibm-application-id: JC-ADPAPI
  description: Enables the ability to send files to ADP for document processing and retrieve the results
  x-ibm-application-icon: <svg width="30" height="30" id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 400 360"><defs><style>.cls-1{fill:#f8b500;}.cls-2{fill:#231815;}</style></defs><title>JRK number</title><path class="cls-1" d="M354.6,295.5H39.4A39.4,39.4,0,0,1,0,256.1V39.4A39.4,39.4,0,0,1,39.4,0H354.6A39.4,39.4,0,0,1,394,39.4V256.1a39.4,39.4,0,0,1-39.4,39.4"/><path class="cls-2" d="M105.85,44.44h45.42V171.75c0,57.37-27.49,77.4-71.72,77.4-10.46,0-24.21-1.8-33.17-4.78l5.08-36.76a74.94,74.94,0,0,0,23.31,3.58c19.12,0,31.08-8.66,31.08-40Z"/><path class="cls-2" d="M337.15,240.18c-8.37,4.19-27.19,8.67-51.7,8.67C215.82,248.85,180,205.52,180,148.14c0-68.74,49-107,110-107,23.6,0,41.53,4.78,49.6,9l-9.26,36.16A98.32,98.32,0,0,0,292,78.81c-36.16,0-64.25,21.81-64.25,66.64,0,40.34,23.9,65.74,64.55,65.74,13.74,0,29-3,37.95-6.57Z"/></svg>

  version: latest
externalDocs:
  url: https://www.ibm.com/docs/en/cloud-paks/cp-biz-automation/23.0.2?topic=integrations-automation-document-processing-api
servers:
  - url: "https://{serverName}.cloud.ibm.com"
    variables:
      serverName:
        default: "ADP Server"
security:
  - bearerAuth: []
paths:
  "/v1/projects/{project_id}/analyzers":
    post:
      summary: JC - Send a PDF to ADP
      description: Send a PDF to ADP
      operationId: sendPDF
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
            x-ibm-disable: true
            x-ibm-show: false
      requestBody:
        content:
          application/json:
      responses:
        '202':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/senddocResponse"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
  "/v1/projects/{project_id}/analyzers/{analyzerId}":
    get:
      summary: JC - Get ADP Status
      description: Get ADP Status
      operationId: getStatus
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
            x-ibm-disable: true
            x-ibm-show: false
        - name: analyzerId
          in: path
          required: true
          schema:
            type: string
            x-ibm-disable: true
            x-ibm-show: false
      responses:
        '202':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/senddocResponse"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
  "/v1/projects/{project_id}/analyzers/{file_id}/json/basic":
    get:
      summary: JC - Get ADP Results
      description: Get ADP Results
      operationId: getResults
      parameters:
        - name: project_id
          in: path
          required: true
          schema:
            type: string
            x-ibm-disable: true
            x-ibm-show: false
        - name: file_id
          in: path
          required: true
          schema:
            type: string
            x-ibm-disable: true
            x-ibm-show: false
      responses:
        '202':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/senddocResponse"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
components:
  schemas:
    requestBody:
      type: object
      required:
        - input
      properties:
        project_id:
          type: string
    senddocResponse:
      description: Successful response
      type: object
      properties:
        results:
          type: array
          items:
            type: object
            properties:
              data:
                properties:
                  filenamein:
                    type: string
                  analyzerid:
                    type: string
    errorResponse:
      description: Unsuccessful response
      type: object
      properties:
        error:
          type: string
        error_description:
          type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: IBM CP4BA Zen API Key